# This is a basic workflow to help you get started with Actions

name: publish to Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.0.6
      - uses: erickzanardo/flutter-gh-pages@v3
